"""Configuration, schema types, aliases, and enrichment patterns."""

from __future__ import annotations

import re

MAX_RETRIES = 3
REQUEST_TIMEOUT_SECONDS = 60.0
# Anthropic output cap; Agents 2/3/5 stay well under this; 1/4 benefit on long visits.
MAX_COMPLETION_TOKENS = 8192
OUTPUT_SUFFIX = "cooperative_multi_agent"

PROVIDER_MODELS = {
    "openrouter": {
        "recall": "openai/gpt-oss-20b",
        "filter": "openai/gpt-oss-20b",
        "negation": "openai/gpt-oss-20b",
        "relation": "openai/gpt-oss-20b",
        "canonicalize": "qwen/qwen3-14b",
    },
    "anthropic": {
        "recall": "claude-sonnet-4-20250514",
        "filter": "claude-sonnet-4-20250514",
        "negation": "claude-sonnet-4-20250514",
        "relation": "claude-sonnet-4-20250514",
        "canonicalize": "claude-sonnet-4-20250514",
    },
}

VALID_NODE_TYPES = frozenset(
    {
        "SYMPTOM",
        "DIAGNOSIS",
        "TREATMENT",
        "PROCEDURE",
        "LOCATION",
        "MEDICAL_HISTORY",
        "LAB_RESULT",
    }
)
VALID_EDGE_TYPES = frozenset(
    {"CAUSES", "INDICATES", "LOCATED_AT", "RULES_OUT", "TAKEN_FOR", "CONFIRMS"}
)

HUMAN_STYLE_GUIDE = """
Human-curated KG style to imitate:
- Nodes are short clinical phrases, usually 1-3 words.
- Use verbose transcript text only in evidence, not in node text.
- Keep patient-concern diagnoses such as covid-19 when explicitly discussed.
- Keep social history, family history, exposures, triggers, and chronic disease.
- Keep brand/product medication names when spoken: tylenol, ventolin, spiriva,
  lisinopril, metformin, lasix, prozac, effexor, neurontin, synthroid, keppra.
- Do not add every normal review-of-systems denial. Add absent findings only when
  clinically salient for the complaint or differential.
- Common canonical terms: nasal congestion, runny nose, cough, fever, fatigue,
  shortness of breath, sore throat, chest pain, wheezing, headache, back pain,
  knee pain, elbow pain, nausea, vomiting, dizziness, edema, palpitations,
  decreased appetite, weight gain, weight loss, depression, anxiety, insomnia,
  hypertension, type 2 diabetes, congestive heart failure, copd, asthma,
  kidney stones, anemia, gastritis, arthritis, gout, lumbar strain,
  chest x-ray, physical exam, cbc, ekg, echocardiogram, mri, ct scan,
  hemoglobin a1c, ejection fraction, blood pressure, blood sugar,
  physical therapy, smoking cessation, dietary modifications, rest, ice,
  smoking, alcohol use, depression history, prior surgery.
- Relation priorities: SYMPTOM INDICATES DIAGNOSIS, TREATMENT TAKEN_FOR condition
  or symptom, SYMPTOM LOCATED_AT body part, PROCEDURE RULES_OUT diagnosis,
  LAB_RESULT CONFIRMS diagnosis, exposure/history CAUSES diagnosis.
""".strip()

CANONICAL_ALIASES = {
    # ── Respiratory / ENT ─────────────────────────────────────────────────────
    "stuffy nose": "nasal congestion",
    "stuffed nose": "nasal congestion",
    "blocked nose": "nasal congestion",
    "congested nose": "nasal congestion",
    "nose congestion": "nasal congestion",
    "rhinorrhea": "runny nose",
    "anosmia": "loss of smell",
    "ageusia": "loss of taste",
    "covid": "covid-19",
    "covid 19": "covid-19",
    "covid-19": "covid-19",
    "coronavirus": "covid-19",
    "covid swab test": "covid swab",
    "covid test swab": "covid swab",
    "covid-19 swab": "covid swab",
    "covid testing": "covid test",
    "swab": "covid swab",
    "common cold": "viral infection / common cold",
    "short of breath": "shortness of breath",
    "difficulty breathing": "shortness of breath",
    "trouble breathing": "shortness of breath",
    "hard to breathe": "shortness of breath",
    "sob": "shortness of breath",
    "dyspnea": "shortness of breath",
    "sputum blood": "hemoptysis",
    "red spots sputum": "hemoptysis",
    "daily puffer": "maintenance inhaler",
    "puffer": "rescue puffer",
    "rescue puffer": "rescue puffer",
    "rescue inhaler": "rescue inhaler",
    "preventer inhaler": "maintenance inhaler",
    "beta agonist": "long acting beta agonist",
    "saltwater gargle": "salt water gargle",
    # ── Imaging / procedures ──────────────────────────────────────────────────
    "xray": "x-ray",
    "x ray": "x-ray",
    "chest xray": "chest x-ray",
    "chest x ray": "chest x-ray",
    "chest x-ray": "chest x-ray",
    "chest radiograph": "chest x-ray",
    "physical examination": "physical exam",
    "lung exam": "physical exam",
    "lung examination": "physical exam",
    "ct": "ct scan",
    "cat scan": "ct scan",
    "ct scan abdomen pelvis": "ct scan abdomen and pelvis",
    "ekg": "ekg",
    "ecg": "ekg",
    "electrocardiogram": "ekg",
    "echo": "echocardiogram",
    "echocardiography": "echocardiogram",
    "pft": "pulmonary function test",
    "pfts": "pulmonary function test",
    "spirometry": "pulmonary function test",
    "complete blood count": "cbc",
    "hemoglobin a1c test": "hemoglobin a1c",
    "hba1c": "hemoglobin a1c",
    "a1c": "hemoglobin a1c",
    "lipid panel test": "lipid panel",
    "cholesterol panel": "lipid panel",
    "ultrasound": "ultrasound",
    "us": "ultrasound",
    "mammography": "mammogram",
    "bloodwork": "laboratory tests",
    "blood work": "laboratory tests",
    "blood tests": "laboratory tests",
    # ── General symptoms ──────────────────────────────────────────────────────
    "dizzy": "dizziness",
    "nauseous": "nausea",
    "tired": "fatigue",
    "exhausted": "fatigue",
    "worn out": "fatigue",
    "red skin": "redness",
    "sore skin": "soreness",
    "swollen": "swelling",
    "puffy": "swelling",
    "bloated": "bloating",
    "throwing up": "vomiting",
    "gaining weight": "weight gain",
    "losing weight": "weight loss",
    "can't sleep": "insomnia",
    "trouble sleeping": "sleep disturbance",
    "feeling down": "depression",
    "feeling anxious": "anxiety",
    "heart racing": "palpitations",
    "racing heart": "palpitations",
    # ── Musculoskeletal ───────────────────────────────────────────────────────
    "low back pain": "lower back pain",
    "lbp": "lower back pain",
    "lumbar pain": "lower back pain",
    "limited range of motion": "decreased range of motion",
    "limited rom": "decreased range of motion",
    "reduced range of motion": "decreased range of motion",
    "positive slr": "positive straight leg raise",
    "lateral epicondylitis": "right elbow lateral epicondylitis",
    "tennis elbow": "lateral epicondylitis",
    "golfers elbow": "medial epicondylitis",
    "joint stiffness": "stiffness",
    "back stiffness": "back stiffness",
    "joint effusion": "effusion",
    # ── Cardiology ────────────────────────────────────────────────────────────
    "chf": "congestive heart failure",
    "heart failure": "congestive heart failure",
    "chf exacerbation": "congestive heart failure exacerbation",
    "cad": "coronary artery disease",
    "ef": "ejection fraction",
    "reduced ef": "decreased ejection fraction",
    "reduced ejection fraction": "decreased ejection fraction",
    "diminished ejection fraction": "decreased ejection fraction",
    "murmur": "systolic ejection murmur",
    "mitral regurg": "mitral regurgitation",
    "mr": "mitral regurgitation",
    "fluid retention": "edema",
    "fluid overload": "edema",
    "leg swelling": "lower extremity edema",
    "ankle swelling": "ankle swelling",
    "peripheral edema": "peripheral edema",
    "pitting edema": "pitting edema",
    "trace edema": "trace pitting edema",
    "lvh": "left ventricular hypertrophy",
    "elevated bp": "elevated blood pressure",
    "bp elevated": "elevated blood pressure",
    # ── GI ────────────────────────────────────────────────────────────────────
    "acid reflux": "acid reflux flare",
    "gerd": "gastroesophageal reflux",
    "heartburn": "acid reflux flare",
    "stomach pain": "abdominal pain",
    "belly pain": "abdominal pain",
    "tummy pain": "abdominal pain",
    "rlq pain": "right lower quadrant tenderness",
    "rlq tenderness": "right lower quadrant tenderness",
    "ruq pain": "right upper quadrant tenderness",
    "ruq tenderness": "right upper quadrant tenderness",
    "blood in stool": "hematochezia",
    "rectal bleeding": "hematochezia",
    "dark stool": "melena",
    "black stool": "melena",
    # ── Endocrinology ─────────────────────────────────────────────────────────
    "type one diabetes": "type 1 diabetes",
    "type i diabetes": "type 1 diabetes",
    "type two diabetes": "type 2 diabetes",
    "type ii diabetes": "type 2 diabetes",
    "type 2 dm": "type 2 diabetes",
    "dm2": "type 2 diabetes",
    "diabetes mellitus": "type 2 diabetes",
    "high blood sugar": "hyperglycemia",
    "elevated blood sugar": "hyperglycemia",
    "blood sugar high": "hyperglycemia",
    "high blood pressure": "hypertension",
    "htn": "hypertension",
    "high cholesterol": "high cholesterol",
    "hyperlipidemia": "high cholesterol",
    "hypercholesterolaemia": "hypercholesterolemia",
    "hypothyroid": "hypothyroidism",
    "underactive thyroid": "hypothyroidism",
    "pre diabetic": "prediabetes",
    "pre-diabetic": "prediabetes",
    # ── Nephrology ────────────────────────────────────────────────────────────
    "kidney stone": "kidney stones",
    "renal calculus": "kidney stones",
    "renal calculi": "kidney stones",
    "nephrolithiasis": "kidney stones",
    "blood in urine": "hematuria",
    "kidney transplant history": "kidney transplant",
    "polycystic kidney disease": "polycystic kidneys",
    "pkd": "polycystic kidneys",
    # ── Psych ─────────────────────────────────────────────────────────────────
    "depressed": "depression",
    "feeling depressed": "depression",
    "major depression": "depression",
    "anxious": "anxiety",
    "generalized anxiety": "anxiety",
    "suicidal thoughts": "suicidal ideation",
    # ── Medications ───────────────────────────────────────────────────────────
    "tylenol cold": "tylenol cold",
    "acetaminophen": "tylenol",
    "advil": "ibuprofen",
    "motrin": "ibuprofen",
    "proton pump inhibitor": "omeprazole",
    "ppi": "omeprazole",
    "prednisone taper": "prednisone taper",
    "pred taper": "prednisone taper",
    "steroid taper": "prednisone taper",
    "water pill": "lasix",
    "furosemide": "lasix",
    "levothyroxine": "synthroid",
    "levetiracetam": "keppra",
    "gabapentin": "neurontin",
    "venlafaxine": "effexor",
    "fluoxetine": "prozac",
    "sertraline": "zoloft",
    "antibiotics prophylaxis": "prophylactic antibiotics",
    "antibiotic treatment": "antibiotics",
    # ── Surgical history ──────────────────────────────────────────────────────
    "gallbladder removal": "cholecystectomy",
    "wisdom teeth extraction": "wisdom teeth removal",
    "wisdom tooth extraction": "wisdom teeth removal",
    "prostate enlargement": "enlarged prostate",
    "cabg": "history of coronary artery bypass graft",
    "bypass surgery": "history of coronary artery bypass graft",
    "rotator cuff surgery": "prior rotator cuff repair",
    "knee replacement": "prior knee arthroplasty",
    "total knee replacement": "prior knee arthroplasty",
    "tkr": "prior knee arthroplasty",
    "disc surgery": "prior discectomy",
    "back surgery": "prior back surgery",
    "spinal fusion": "prior lumbar fusion",
    "neck surgery": "prior neck surgery",
    "cataract surgery": "prior cataract extraction",
    # ── Misc ──────────────────────────────────────────────────────────────────
    "isolation for 14 days": "14-day isolation",
    "self isolation": "self-isolation",
    "class exposure": "school exposure",
    "cat allergy": "possible cat allergy",
    "pet cat": "possible cat allergy",
    "father heart attack": "family history heart attack",
    "cold air": "cold air trigger",
    "cold weather": "cold air trigger",
    "pollen": "pollen trigger",
    "exercise": "exercise trigger",
    "tick bite location: behind left knee": "behind left knee",
    "car accident": "motor vehicle accident",
    "mva": "motor vehicle accident",
    "auto accident": "motor vehicle accident",
    "afib": "atrial fibrillation",
    "a fib": "atrial fibrillation",
    "a-fib": "atrial fibrillation",
    "seasonal allergy": "seasonal allergies",
    "hay fever": "seasonal allergies",
}

LOW_VALUE_NEGATION_RE = re.compile(
    r"^(absent|no)\s+("
    r"travel|sick contacts?|pets?|mold|dust|asbestos|old carpets?|"
    r"recreational drugs?|marijuana use|medications?|other drugs?|"
    r"developmental delays?|environmental exposures?|family history of "
    r"(respiratory problems|lung disease|other allergies|sudden death)|"
    r"vision/hearing changes|blood in stool|blood in vomit|bloating/gas|"
    r"confusion(/memory loss)?|bowel changes|urinary symptoms|sexual activity|"
    r"surgeries|iv drugs|flu shot|skin changes|cough triggers|other triggers|"
    r"other allergies|previous chest pain|previous hospital|previous cough"
    r")$"
)

ENRICHMENT_PATTERNS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    ("SYMPTOM", "yellow sputum", r"\byellow (?:phlegm|sputum|mucus)\b", ("yellow",)),
    ("SYMPTOM", "green sputum", r"\bgreen (?:phlegm|sputum|mucus)\b", ("green",)),
    ("SYMPTOM", "mucus production", r"\b(?:mucus|phlegm|sputum)\b", ("mucus", "phlegm", "sputum")),
    ("SYMPTOM", "loss of taste", r"\bloss of (?:sense of )?taste\b|\bcan't taste\b", ("taste",)),
    ("SYMPTOM", "loss of smell", r"\bloss of (?:sense of )?smell\b|\bcan't smell\b", ("smell",)),
    ("SYMPTOM", "hemoptysis", r"\b(?:blood|red spots?) (?:in|with) (?:sputum|phlegm|mucus)\b", ("blood",)),
    ("SYMPTOM", "worsening cough", r"\b(?:cough|coughing).{0,40}(?:worse|worsening|progressively)\b", ("cough",)),
    ("SYMPTOM", "pleuritic chest pain", r"\bchest pain\b.{0,60}\b(?:deep breath|breathing|cough|coughing)\b", ("chest pain",)),
    ("SYMPTOM", "subjective fever", r"\b(?:felt|feel|feeling) feverish\b", ("feverish",)),
    ("SYMPTOM", "decreased appetite", r"\b(?:decreased|reduced|low|poor) appetite\b", ("appetite",)),
    ("SYMPTOM", "nocturnal wheezing", r"\b(?:wheez(?:e|ing)).{0,40}\b(?:night|nighttime|sleep)\b", ("wheez",)),
    ("SYMPTOM", "difficulty deep breathing", r"\b(?:difficult|hard|trouble).{0,30}\bdeep breath", ("deep breath",)),
    ("SYMPTOM", "breathing faster", r"\bbreath(?:ing)? faster\b|\bfast breathing\b", ("breathing",)),
    ("SYMPTOM", "redness", r"\bred(?:ness)?\b", ("red",)),
    ("SYMPTOM", "tenderness", r"\btender(?:ness)?\b", ("tender",)),
    ("SYMPTOM", "soreness", r"\bsore(?:ness)?\b", ("sore",)),
    ("SYMPTOM", "flu-like symptoms", r"\bflu[- ]like symptoms?\b", ("flu-like",)),
    ("SYMPTOM", "chest soreness", r"\bchest sore(?:ness)?\b|\bsore chest\b", ("chest sore", "sore chest")),
    ("SYMPTOM", "rash", r"\brash\b", ("rash",)),
    ("SYMPTOM", "no fever", r"\bno fever\b", ("no fever",)),
    ("SYMPTOM", "absent abdominal pain", r"\bno abdominal pain\b|\bdenies abdominal pain\b", ("abdominal pain",)),
    ("SYMPTOM", "absent back or muscle pain", r"\bno (?:back|muscle) pain\b|\bdenies (?:back|muscle) pain\b", ("back pain", "muscle pain")),
    ("SYMPTOM", "absent joint pain", r"\bno joint pain\b|\bdenies joint pain\b", ("joint pain",)),
    ("SYMPTOM", "chest pain (absent)", r"\bno chest pain\b|\bdenies chest pain\b", ("no chest pain",)),
    ("DIAGNOSIS", "viral infection / common cold", r"\bviral infection\b.{0,30}\bcommon cold\b|\bcommon cold\b", ("common cold",)),
    ("DIAGNOSIS", "viral illness", r"\bviral illness\b", ("viral illness",)),
    ("DIAGNOSIS", "upper respiratory infection", r"\bupper respiratory infection\b|\buri\b", ("upper respiratory",)),
    ("DIAGNOSIS", "respiratory infection", r"\brespiratory infection\b", ("respiratory infection",)),
    ("DIAGNOSIS", "asthma exacerbation", r"\basthma exacerbation\b", ("asthma exacerbation",)),
    ("DIAGNOSIS", "asthma ruled out", r"\basthma\b.{0,30}\bruled out\b|\brule out asthma\b", ("ruled out asthma",)),
    ("DIAGNOSIS", "suspected infection", r"\bsuspected infection\b|\bconcern(?:ed)? for infection\b", ("suspected infection",)),
    ("DIAGNOSIS", "suspected allergies", r"\bsuspected allergies\b|\blikely allergies\b", ("allergies",)),
    ("DIAGNOSIS", "cardiac ischemia", r"\bcardiac ischemia\b|\bischemia\b", ("ischemia",)),
    ("DIAGNOSIS", "heart disease concern", r"\b(?:heart disease|heart attack|cardiac).{0,40}\b(?:concern|worried|worry)\b", ("heart",)),
    ("DIAGNOSIS", "tick bite", r"\btick bite\b|\btick\b.{0,30}\b(?:bite|bit)", ("tick",)),
    ("TREATMENT", "decongestants", r"\bdecongestants?\b", ("decongestant",)),
    ("TREATMENT", "nsaids", r"\bnsaids?\b|\bnon[- ]steroidal\b", ("nsaid",)),
    ("TREATMENT", "ventolin", r"\bventolin\b", ("ventolin",)),
    ("TREATMENT", "spiriva", r"\bspiriva\b", ("spiriva",)),
    ("TREATMENT", "atorvastatin", r"\batorvastatin\b", ("atorvastatin",)),
    ("TREATMENT", "diuretic", r"\bdiuretics?\b", ("diuretic",)),
    ("TREATMENT", "supplemental oxygen", r"\bsupplemental oxygen\b|\boxygen\b", ("oxygen",)),
    ("TREATMENT", "steroids", r"\bsteroids?\b|\bprednisone\b", ("steroid", "prednisone")),
    ("TREATMENT", "antibiotics", r"\bantibiotics?\b", ("antibiotic",)),
    ("TREATMENT", "long acting beta agonist", r"\blong[- ]acting beta agonist\b|\blaba\b", ("beta agonist", "laba")),
    ("TREATMENT", "inhalers", r"\binhalers\b", ("inhalers",)),
    ("TREATMENT", "salt water gargle", r"\bsalt ?water gargle\b", ("gargle",)),
    ("TREATMENT", "painkillers", r"\bpain ?killers?\b|\bpain medications?\b", ("pain",)),
    ("TREATMENT", "14-day isolation", r"\b14[- ]day isolation\b|\bisolat(?:e|ion).{0,20}\b14 days\b", ("14", "isolation")),
    ("TREATMENT", "self-isolation", r"\bself[- ]isolation\b|\bstay isolated\b", ("isolated", "isolation")),
    ("TREATMENT", "dietary modification", r"\bdiet(?:ary)? modifications?\b|\bchange (?:your )?diet\b", ("diet",)),
    ("TREATMENT", "maintenance inhaler", r"\bmaintenance inhaler\b|\bdaily puffer\b|\bpreventer inhaler\b", ("maintenance", "daily puffer")),
    ("TREATMENT", "rescue inhaler", r"\brescue inhaler\b", ("rescue inhaler",)),
    ("TREATMENT", "rescue puffer", r"\brescue puffer\b", ("rescue puffer",)),
    ("TREATMENT", "lifestyle modifications", r"\blifestyle modifications?\b", ("lifestyle",)),
    ("TREATMENT", "allergy shots", r"\ballergy shots?\b", ("allergy shot",)),
    ("TREATMENT", "prophylactic antibiotics", r"\bprophylactic antibiotics?\b", ("prophylactic",)),
    ("TREATMENT", "penicillin", r"\bpenicillin\b", ("penicillin",)),
    ("TREATMENT", "vitamins", r"\bvitamins?\b", ("vitamin",)),
    ("TREATMENT", "oral contraceptive (deyo)", r"\bdeyo\b|\boral contraceptive\b|\bbirth control\b", ("deyo", "birth control")),
    ("TREATMENT", "statin", r"\bstatins?\b", ("statin",)),
    ("PROCEDURE", "cbc", r"\bcbc\b", ("cbc",)),
    ("PROCEDURE", "electrolytes", r"\belectrolytes?\b", ("electrolyte",)),
    ("PROCEDURE", "kidney function test", r"\bkidney function(?: test)?\b|\bcreatinine\b", ("kidney",)),
    ("PROCEDURE", "abg", r"\babg\b|\barterial blood gas\b", ("abg", "arterial blood gas")),
    ("PROCEDURE", "pulse oximetry", r"\bpulse ox(?:imetry)?\b|\bo2 sat\b|\boxygen saturation\b", ("pulse", "oxygen saturation")),
    ("PROCEDURE", "chest auscultation", r"\bchest auscultation\b|\blisten(?:ing)? to (?:your )?chest\b", ("chest", "listen")),
    ("PROCEDURE", "vital signs", r"\bvital signs?\b", ("vital",)),
    ("PROCEDURE", "lyme serology", r"\blyme serology\b|\blyme blood test\b", ("lyme",)),
    ("MEDICAL_HISTORY", "hypertension history", r"\bhistory of hypertension\b|\bhypertension history\b", ("hypertension",)),
    ("MEDICAL_HISTORY", "mononucleosis", r"\bmononucleosis\b|\bmono\b", ("mono",)),
    ("MEDICAL_HISTORY", "school exposure", r"\b(?:school|class|classmate)\b.{0,60}\b(?:sick|exposure|cold)\b", ("school", "class")),
    ("MEDICAL_HISTORY", "hiking exposure", r"\bhik(?:e|ing)\b", ("hiking", "hike")),
    ("MEDICAL_HISTORY", "hay fever", r"\bhay fever\b", ("hay fever",)),
    ("MEDICAL_HISTORY", "hospital worker", r"\bhospital\b.{0,30}\bwork", ("hospital",)),
    ("MEDICAL_HISTORY", "prior er visits", r"\b(?:er|emergency).{0,30}\bvisits?\b", ("er", "emergency")),
    ("MEDICAL_HISTORY", "missed medication dose", r"\bmissed\b.{0,30}\b(?:dose|medication)\b", ("missed",)),
    ("MEDICAL_HISTORY", "exercise trigger", r"\bexercise\b.{0,30}\btrigger\b|\btrigger(?:ed)? by exercise\b", ("exercise",)),
    ("MEDICAL_HISTORY", "cold air trigger", r"\bcold air\b|\bcold weather\b", ("cold air", "cold weather")),
    ("MEDICAL_HISTORY", "pollen trigger", r"\bpollen\b", ("pollen",)),
    ("MEDICAL_HISTORY", "chemical plant work", r"\bchemical plant\b", ("chemical",)),
    ("MEDICAL_HISTORY", "family hx allergies (father)", r"\bfather\b.{0,40}\ballerg", ("father", "allerg")),
    ("MEDICAL_HISTORY", "family hx asthma (cousin)", r"\bcousin\b.{0,40}\basthma", ("cousin", "asthma")),
    ("MEDICAL_HISTORY", "brother had cold", r"\bbrother\b.{0,40}\bcold", ("brother", "cold")),
    ("MEDICAL_HISTORY", "possible cat allergy", r"\bcat\b.{0,40}\ballerg", ("cat", "allerg")),
    ("MEDICAL_HISTORY", "family history heart attack", r"\b(?:father|mother|family).{0,50}\bheart attack\b", ("heart attack",)),
    ("MEDICAL_HISTORY", "sick contact - husband", r"\bhusband\b.{0,50}\b(?:sick|cold|cough)", ("husband",)),
    ("MEDICAL_HISTORY", "carpets in home", r"\bcarpets?\b", ("carpet",)),
    ("MEDICAL_HISTORY", "prior tick bite", r"\bprior\b.{0,30}\btick bite\b|\btick bite\b.{0,30}\bbefore\b", ("tick",)),
    ("MEDICAL_HISTORY", "prior bullseye rash", r"\bbullseye rash\b", ("bullseye",)),
    ("MEDICAL_HISTORY", "gardening exposure", r"\bgarden(?:ing)?\b", ("garden",)),
    # ── Musculoskeletal symptoms ─────────────────────────────────────────────
    ("SYMPTOM", "back pain", r"\bback pain\b", ("back pain",)),
    ("SYMPTOM", "lower back pain", r"\b(?:low(?:er)?|lumbar) back pain\b|\blbp\b", ("back pain",)),
    ("SYMPTOM", "back stiffness", r"\bback stiffness\b|\bstiff(?:ness)? (?:in )?(?:my |the )?back\b", ("stiff", "back")),
    ("SYMPTOM", "knee pain", r"\bknee pain\b", ("knee pain",)),
    ("SYMPTOM", "right knee pain", r"\bright knee pain\b", ("right knee",)),
    ("SYMPTOM", "elbow pain", r"\belbow pain\b", ("elbow pain",)),
    ("SYMPTOM", "right elbow pain", r"\bright elbow pain\b", ("right elbow",)),
    ("SYMPTOM", "joint pain", r"\bjoint pain\b|\barthralgia\b", ("joint pain",)),
    ("SYMPTOM", "decreased range of motion", r"\b(?:decreased|limited|reduced) (?:range of motion|rom)\b", ("range of motion",)),
    ("SYMPTOM", "positive straight leg raise", r"\bstraight leg raise\b|\bslr\b", ("straight leg",)),
    ("SYMPTOM", "lumbar tenderness", r"\blumbar tenderness\b|\btenderness.{0,30}lumbar\b", ("lumbar", "tender")),
    ("SYMPTOM", "right knee effusion", r"\bknee effusion\b|\beffusion.{0,20}knee\b", ("effusion", "knee")),
    ("SYMPTOM", "right knee erythema", r"\bknee.{0,20}(?:red(?:ness)?|erythema)\b", ("knee", "red")),
    ("SYMPTOM", "drop foot", r"\bdrop foot\b|\bfoot drop\b", ("drop foot", "foot drop")),
    ("SYMPTOM", "bruising", r"\bbruis(?:e|ing)\b", ("bruis",)),
    ("SYMPTOM", "swelling", r"\bswell(?:ing|ed)\b", ("swell",)),
    # ── Cardiology symptoms ───────────────────────────────────────────────────
    ("SYMPTOM", "chest pain", r"\bchest pain\b", ("chest pain",)),
    ("SYMPTOM", "palpitations", r"\bpalpitations?\b|\bheart rac(?:e|ing)\b", ("palpitation", "heart rac")),
    ("SYMPTOM", "dyspnea on exertion", r"\b(?:shortness of breath|dyspnea|sob).{0,30}(?:exertion|exercise|walking|stairs)\b", ("exertion",)),
    ("SYMPTOM", "peripheral edema", r"\bperipheral edema\b|\bleg swell(?:ing)?\b", ("peripheral edema", "leg swell")),
    ("SYMPTOM", "bilateral lower extremity edema", r"\bbilateral.{0,20}(?:lower extremity|leg).{0,10}edema\b", ("bilateral", "edema")),
    ("SYMPTOM", "pitting edema", r"\bpitting edema\b", ("pitting",)),
    ("SYMPTOM", "ankle swelling", r"\bankle swell(?:ing)?\b", ("ankle",)),
    ("SYMPTOM", "weight gain", r"\bweight gain\b|\bgain(?:ed|ing) weight\b", ("weight gain",)),
    ("SYMPTOM", "systolic ejection murmur", r"\bsystolic.{0,10}(?:ejection )?murmur\b|\bmurmur\b", ("murmur",)),
    ("SYMPTOM", "fine crackles", r"\bfine crackles?\b|\bcrackles?\b", ("crackle",)),
    ("SYMPTOM", "carotid bruit", r"\bcarotid bruit\b|\bbruit\b", ("bruit",)),
    # ── GI symptoms ───────────────────────────────────────────────────────────
    ("SYMPTOM", "abdominal pain", r"\babdominal pain\b|\bstomach (?:pain|ache)\b|\bbelly pain\b", ("abdominal pain", "stomach")),
    ("SYMPTOM", "nausea", r"\bnausea\b|\bnauseous\b", ("nausea",)),
    ("SYMPTOM", "vomiting", r"\bvomiting\b|\bthrow(?:ing)? up\b", ("vomit",)),
    ("SYMPTOM", "bloating", r"\bbloat(?:ing|ed)?\b", ("bloat",)),
    ("SYMPTOM", "hematuria", r"\bhematuria\b|\bblood in (?:the )?urine\b", ("hematuria", "blood in urine")),
    ("SYMPTOM", "right lower quadrant tenderness", r"\bright lower quadrant.{0,10}tender\b|\brlq.{0,10}tender\b", ("right lower quadrant",)),
    ("SYMPTOM", "right upper quadrant tenderness", r"\bright upper quadrant.{0,10}tender\b|\bruq.{0,10}tender\b", ("right upper quadrant",)),
    ("SYMPTOM", "cva tenderness", r"\bcva tenderness\b|\bcostovertebral.{0,10}tender\b", ("cva",)),
    # ── Neuro / psych symptoms ────────────────────────────────────────────────
    ("SYMPTOM", "depression", r"\bdepression\b|\bdepressed\b|\bfeeling down\b", ("depress",)),
    ("SYMPTOM", "anxiety", r"\banxiety\b|\banxious\b", ("anxi",)),
    ("SYMPTOM", "sleep disturbance", r"\b(?:trouble|difficulty|can't|cannot) sleep(?:ing)?\b|\binsomnia\b", ("sleep",)),
    ("SYMPTOM", "lightheadedness", r"\blightheaded(?:ness)?\b", ("lightheaded",)),
    ("SYMPTOM", "dizziness", r"\bdizz(?:y|iness)\b", ("dizz",)),
    ("SYMPTOM", "fatigue", r"\bfatigue\b|\btired\b|\bexhaust(?:ed|ion)\b", ("fatigu", "tired")),
    ("SYMPTOM", "high blood sugar", r"\b(?:high|elevated) blood sugar\b|\bblood sugar.{0,10}(?:high|elevated|300)\b", ("blood sugar",)),
    ("SYMPTOM", "mild thyromegaly", r"\bthyromegaly\b|\benlarged thyroid\b", ("thyromegaly", "thyroid")),
    # ── Dermatology ───────────────────────────────────────────────────────────
    ("SYMPTOM", "erythema", r"\berythema\b", ("erythema",)),
    ("SYMPTOM", "fluctuance", r"\bfluctuance\b", ("fluctuance",)),
    ("SYMPTOM", "insect bite", r"\binsect bite\b|\bbug bite\b", ("insect bite", "bug bite")),
    # ── Absent findings (broader scope) ───────────────────────────────────────
    ("SYMPTOM", "absent fever", r"\b(?:no|denies?) fever\b", ("no fever",)),
    ("SYMPTOM", "absent chest pain", r"\b(?:no|denies?) chest pain\b", ("no chest pain",)),
    ("SYMPTOM", "absent shortness of breath", r"\b(?:no|denies?) (?:shortness of breath|sob|dyspnea)\b", ("no shortness",)),
    ("SYMPTOM", "absent nausea", r"\b(?:no|denies?) nausea\b", ("no nausea",)),
    ("SYMPTOM", "absent vomiting", r"\b(?:no|denies?) vomiting\b", ("no vomiting",)),
    ("SYMPTOM", "absent headache", r"\b(?:no|denies?) headache\b", ("no headache",)),
    ("SYMPTOM", "absent edema", r"\b(?:no|denies?).{0,10}edema\b|\bno (?:leg )?swell(?:ing)?\b", ("no edema",)),
    ("SYMPTOM", "absent hematochezia", r"\b(?:no|denies?) hematochezia\b|\bno blood in stool\b", ("no hematochezia",)),
    ("SYMPTOM", "absent weight loss", r"\b(?:no|denies?).{0,10}weight loss\b", ("no weight loss",)),
    ("SYMPTOM", "absent night sweats", r"\b(?:no|denies?) night sweats?\b", ("no night sweat",)),
    # ── Diagnoses ─────────────────────────────────────────────────────────────
    ("DIAGNOSIS", "congestive heart failure exacerbation", r"\b(?:chf|congestive heart failure|heart failure).{0,20}exacerbation\b", ("heart failure", "exacerbation")),
    ("DIAGNOSIS", "coronary artery disease", r"\bcoronary artery disease\b|\bcad\b", ("coronary", "cad")),
    ("DIAGNOSIS", "anemia", r"\banemia\b", ("anemia",)),
    ("DIAGNOSIS", "gastritis", r"\bgastritis\b", ("gastritis",)),
    ("DIAGNOSIS", "gastric polyp", r"\bgastric polyp\b|\bstomach polyp\b", ("polyp",)),
    ("DIAGNOSIS", "kidney stones recurrence", r"\bkidney stone\b.{0,30}\b(?:recur|again|another)\b", ("kidney stone",)),
    ("DIAGNOSIS", "lumbar strain", r"\blumbar strain\b", ("lumbar strain",)),
    ("DIAGNOSIS", "acute lumbar strain", r"\bacute lumbar strain\b", ("acute lumbar",)),
    ("DIAGNOSIS", "arthritis exacerbation", r"\barthritis.{0,20}(?:exacerbation|flare|worse)\b", ("arthritis",)),
    ("DIAGNOSIS", "right elbow lateral epicondylitis", r"\blateral epicondylitis\b|\btennis elbow\b", ("epicondylitis",)),
    ("DIAGNOSIS", "right leg contusion", r"\bleg contusion\b|\bcontusion.{0,20}leg\b", ("contusion",)),
    ("DIAGNOSIS", "hyperglycemia", r"\bhyperglycemia\b|\bhigh (?:blood )?sugar\b|\bblood sugar.{0,10}(?:high|elevated|300)\b", ("hyperglycemia", "blood sugar")),
    ("DIAGNOSIS", "newly diagnosed diabetes", r"\bnewly diagnosed diabetes\b|\bnew.{0,10}diabetes\b", ("newly", "diabetes")),
    ("DIAGNOSIS", "uncontrolled hypertension", r"\buncontrolled.{0,10}(?:hypertension|blood pressure|htn)\b", ("uncontrolled",)),
    ("DIAGNOSIS", "hypertension", r"\bhypertension\b|\bhtn\b|\bhigh blood pressure\b", ("hypertension",)),
    ("DIAGNOSIS", "lyme disease", r"\blyme disease\b", ("lyme",)),
    ("DIAGNOSIS", "strep infection", r"\bstrep (?:infection|throat)\b", ("strep",)),
    ("DIAGNOSIS", "acid reflux flare", r"\bacid reflux\b|\bgerd\b|\bheartburn\b", ("acid reflux", "gerd")),
    ("DIAGNOSIS", "copd", r"\bcopd\b|\bchronic obstructive\b", ("copd",)),
    ("DIAGNOSIS", "pumping dysfunction", r"\bpumping.{0,15}(?:dysfunction|function|problem)\b|\blow.{0,10}(?:pumping|ef|ejection)\b", ("pumping",)),
    # ── Treatments (ACI-Bench medications) ────────────────────────────────────
    ("TREATMENT", "ibuprofen", r"\bibuprofen\b|\badvil\b|\bmotrin\b", ("ibuprofen", "advil", "motrin")),
    ("TREATMENT", "tylenol", r"\btylenol\b|\bacetaminophen\b", ("tylenol", "acetaminophen")),
    ("TREATMENT", "metformin", r"\bmetformin\b", ("metformin",)),
    ("TREATMENT", "lisinopril", r"\blisinopril\b", ("lisinopril",)),
    ("TREATMENT", "lasix", r"\blasix\b|\bfurosemide\b", ("lasix", "furosemide")),
    ("TREATMENT", "carvedilol", r"\bcarvedilol\b|\bcoreg\b", ("carvedilol",)),
    ("TREATMENT", "digoxin", r"\bdigoxin\b", ("digoxin",)),
    ("TREATMENT", "aspirin", r"\baspirin\b", ("aspirin",)),
    ("TREATMENT", "norvasc", r"\bnorvasc\b|\bamlodipine\b", ("norvasc", "amlodipine")),
    ("TREATMENT", "toprol", r"\btoprol\b|\bmetoprolol\b", ("toprol", "metoprolol")),
    ("TREATMENT", "omeprazole", r"\bomeprazole\b|\bprilosec\b", ("omeprazole",)),
    ("TREATMENT", "protonix", r"\bprotonix\b|\bpantoprazole\b", ("protonix",)),
    ("TREATMENT", "pepcid", r"\bpepcid\b|\bfamotidine\b", ("pepcid",)),
    ("TREATMENT", "prozac", r"\bprozac\b|\bfluoxetine\b", ("prozac",)),
    ("TREATMENT", "effexor", r"\beffexor\b|\bvenlafaxine\b", ("effexor",)),
    ("TREATMENT", "zoloft", r"\bzoloft\b|\bsertraline\b", ("zoloft",)),
    ("TREATMENT", "neurontin", r"\bneurontin\b|\bgabapentin\b", ("neurontin", "gabapentin")),
    ("TREATMENT", "keppra", r"\bkeppra\b|\blevetiracetam\b", ("keppra",)),
    ("TREATMENT", "synthroid", r"\bsynthroid\b|\blevothyroxine\b", ("synthroid",)),
    ("TREATMENT", "allopurinol", r"\ballopurinol\b", ("allopurinol",)),
    ("TREATMENT", "meloxicam", r"\bmeloxicam\b|\bmobic\b", ("meloxicam", "mobic")),
    ("TREATMENT", "tramadol", r"\btramadol\b|\bultram\b", ("tramadol", "ultram")),
    ("TREATMENT", "lortab", r"\blortab\b|\bhydrocodone\b", ("lortab",)),
    ("TREATMENT", "amoxicillin", r"\bamoxicillin\b", ("amoxicillin",)),
    ("TREATMENT", "prednisone taper", r"\bprednisone taper\b|\btaper.{0,10}prednisone\b|\bsteroid taper\b", ("prednisone taper",)),
    ("TREATMENT", "combivent", r"\bcombivent\b", ("combivent",)),
    ("TREATMENT", "albuterol inhaler", r"\balbuterol\b", ("albuterol",)),
    ("TREATMENT", "symbicort", r"\bsymbicort\b", ("symbicort",)),
    ("TREATMENT", "epipen", r"\bepipen\b|\bepinephrine auto\b", ("epipen",)),
    ("TREATMENT", "physical therapy", r"\bphysical therapy\b|\bpt\b.{0,20}\btherapy\b", ("physical therapy",)),
    ("TREATMENT", "rest", r"\brest\b.{0,20}\b(?:recommend|prescrib|advis|instruct)\b", ("rest",)),
    ("TREATMENT", "ice", r"\bice\b.{0,20}\b(?:recommend|apply|instruct)\b|\bapply(?:ing)? ice\b", ("ice",)),
    ("TREATMENT", "sling", r"\bsling\b", ("sling",)),
    ("TREATMENT", "finger splint", r"\bfinger splint\b|\bsplint\b.{0,20}finger\b", ("splint",)),
    ("TREATMENT", "smoking cessation", r"\bsmoking cessation\b|\bquit smoking\b|\bstop smoking\b", ("smoking cessation", "quit smoking")),
    ("TREATMENT", "home exercise", r"\bhome exercise\b|\bexercise.{0,20}(?:at home|program)\b", ("home exercise",)),
    ("TREATMENT", "hydration", r"\bhydrat(?:e|ion)\b|\bdrink.{0,20}(?:fluids?|water)\b", ("hydrat",)),
    ("TREATMENT", "dietary modifications", r"\bdiet(?:ary)? (?:modifications?|changes?)\b|\bchange.{0,10}diet\b", ("diet",)),
    ("TREATMENT", "home blood sugar monitoring", r"\bmonitor.{0,20}blood sugar\b|\bcheck.{0,20}blood sugar\b", ("blood sugar", "monitor")),
    ("TREATMENT", "weekly counseling", r"\b(?:weekly|regular) counseling\b", ("counseling",)),
    ("TREATMENT", "weekly therapy", r"\b(?:weekly|regular) therapy\b", ("therapy",)),
    # ── Procedures (ACI-Bench) ────────────────────────────────────────────────
    ("PROCEDURE", "ekg", r"\bekg\b|\becg\b|\belectrocardiogram\b", ("ekg", "ecg")),
    ("PROCEDURE", "echocardiogram", r"\bechocardiogram\b|\becho\b", ("echo",)),
    ("PROCEDURE", "cardiac catheterization", r"\bcardiac cath(?:eterization)?\b|\bheart cath\b", ("cardiac cath",)),
    ("PROCEDURE", "ct scan", r"\bct scan\b|\bcat scan\b|\bct\b", ("ct scan",)),
    ("PROCEDURE", "ct scan abdomen and pelvis", r"\bct.{0,10}(?:abdomen|abd).{0,10}pelvis\b", ("ct", "abdomen")),
    ("PROCEDURE", "mri", r"\bmri\b|\bmagnetic resonance\b", ("mri",)),
    ("PROCEDURE", "lumbar mri", r"\blumbar mri\b|\bmri.{0,10}(?:lumbar|spine|back)\b", ("mri", "lumbar")),
    ("PROCEDURE", "lumbar spine x-ray", r"\blumbar.{0,10}(?:x-?ray|xray|x ray)\b|\bspine.{0,10}(?:x-?ray|xray)\b", ("lumbar", "x-ray")),
    ("PROCEDURE", "right knee x-ray", r"\b(?:right )?knee.{0,10}(?:x-?ray|xray)\b", ("knee", "x-ray")),
    ("PROCEDURE", "right elbow x-ray", r"\b(?:right )?elbow.{0,10}(?:x-?ray|xray)\b", ("elbow", "x-ray")),
    ("PROCEDURE", "right humerus x-ray", r"\bhumerus.{0,10}(?:x-?ray|xray)\b|\b(?:x-?ray|xray).{0,10}humerus\b", ("humerus", "x-ray")),
    ("PROCEDURE", "right middle finger x-ray", r"\bfinger.{0,10}(?:x-?ray|xray)\b", ("finger", "x-ray")),
    ("PROCEDURE", "right lower extremity x-ray", r"\b(?:lower extremity|leg).{0,10}(?:x-?ray|xray)\b", ("lower extremity", "x-ray")),
    ("PROCEDURE", "abdominal x-ray", r"\babdominal.{0,10}(?:x-?ray|xray)\b|\b(?:x-?ray|xray).{0,10}abdomen\b", ("abdominal", "x-ray")),
    ("PROCEDURE", "right upper quadrant ultrasound", r"\b(?:right upper quadrant|ruq).{0,10}(?:ultrasound|us)\b", ("ultrasound",)),
    ("PROCEDURE", "colonoscopy", r"\bcolonoscopy\b", ("colonoscopy",)),
    ("PROCEDURE", "endoscopy", r"\bendoscopy\b|\begd\b", ("endoscopy",)),
    ("PROCEDURE", "polypectomy", r"\bpolypectomy\b", ("polypectomy",)),
    ("PROCEDURE", "hemoglobin a1c", r"\b(?:hemoglobin )?a1c\b|\bhba1c\b", ("a1c",)),
    ("PROCEDURE", "lipid panel", r"\blipid panel\b|\bcholesterol panel\b", ("lipid",)),
    ("PROCEDURE", "diabetes panel", r"\bdiabetes panel\b|\bdiabetic labs?\b", ("diabetes panel",)),
    ("PROCEDURE", "thyroid panel", r"\bthyroid panel\b|\bthyroid function\b|\btsh\b", ("thyroid",)),
    ("PROCEDURE", "anemia profile", r"\banemia (?:profile|workup|panel)\b", ("anemia",)),
    ("PROCEDURE", "glucose test", r"\bglucose (?:test|level)\b|\bfasting glucose\b", ("glucose",)),
    ("PROCEDURE", "lyme titer", r"\blyme titer\b|\blyme test\b", ("lyme titer",)),
    ("PROCEDURE", "rapid strep test", r"\brapid strep\b|\bstrep test\b", ("strep test",)),
    ("PROCEDURE", "western blot pcr", r"\bwestern blot\b|\bpcr\b", ("western blot", "pcr")),
    ("PROCEDURE", "mammogram", r"\bmammogram\b|\bmammography\b", ("mammogram",)),
    # ── Medical history (ACI-Bench) ───────────────────────────────────────────
    ("MEDICAL_HISTORY", "congestive heart failure", r"\b(?:congestive heart failure|chf)\b.{0,30}\bhistory\b|\bhistory.{0,30}\b(?:chf|congestive heart failure)\b|\bpmh.{0,60}\b(?:chf|heart failure)\b", ("chf", "heart failure")),
    ("MEDICAL_HISTORY", "type 2 diabetes", r"\b(?:type 2 diabetes|type ii diabetes|dm2|t2dm)\b", ("type 2 diabetes", "dm2")),
    ("MEDICAL_HISTORY", "depression history", r"\bhistory of depression\b|\bdepression.{0,20}history\b|\bpmh.{0,60}depression\b", ("depression", "history")),
    ("MEDICAL_HISTORY", "anxiety history", r"\bhistory of anxiety\b|\banxiety.{0,20}history\b", ("anxiety", "history")),
    ("MEDICAL_HISTORY", "hypothyroidism", r"\bhypothyroidism\b|\bhypothyroid\b|\bunderactive thyroid\b", ("hypothyroid",)),
    ("MEDICAL_HISTORY", "kidney transplant", r"\bkidney transplant\b|\brenal transplant\b", ("kidney transplant",)),
    ("MEDICAL_HISTORY", "kidney stones", r"\bkidney stones?\b|\brenal calcul[ui]\b|\bnephrolithiasis\b", ("kidney stone",)),
    ("MEDICAL_HISTORY", "arthritis", r"\barthritis\b|\bosteoarthritis\b|\boa\b", ("arthritis",)),
    ("MEDICAL_HISTORY", "gout", r"\bgout\b", ("gout",)),
    ("MEDICAL_HISTORY", "gastroesophageal reflux", r"\bgastroesophageal reflux\b|\bgerd\b", ("gerd",)),
    ("MEDICAL_HISTORY", "diverticulosis", r"\bdiverticulosis\b|\bdiverticular\b", ("diverticul",)),
    ("MEDICAL_HISTORY", "atrial fibrillation", r"\batrial fibrillation\b|\bafib\b|\ba-?fib\b", ("atrial fibrillation", "afib")),
    ("MEDICAL_HISTORY", "atopic eczema", r"\beczema\b|\batopic dermatitis\b", ("eczema",)),
    ("MEDICAL_HISTORY", "epilepsy", r"\bepilepsy\b|\bseizure disorder\b", ("epilepsy", "seizure")),
    ("MEDICAL_HISTORY", "polycystic kidneys", r"\bpolycystic kidney\b|\bpkd\b", ("polycystic",)),
    ("MEDICAL_HISTORY", "anaphylaxis history", r"\banaphylaxis\b|\banaphylactic\b", ("anaphylaxis",)),
    ("MEDICAL_HISTORY", "gallstones", r"\bgallstones?\b|\bcholelithiasis\b", ("gallstone",)),
    ("MEDICAL_HISTORY", "migraines", r"\bmigraines?\b", ("migraine",)),
    ("MEDICAL_HISTORY", "prior back surgery", r"\b(?:prior|previous|past).{0,15}back surgery\b|\bback surgery\b.{0,15}\b(?:history|prior|past)\b", ("back surgery",)),
    ("MEDICAL_HISTORY", "prior discectomy", r"\bdiscectomy\b", ("discectomy",)),
    ("MEDICAL_HISTORY", "prior lumbar fusion", r"\b(?:lumbar|spinal) fusion\b", ("fusion",)),
    ("MEDICAL_HISTORY", "prior knee arthroplasty", r"\bknee (?:arthroplasty|replacement)\b|\btkr\b", ("arthroplasty", "knee replacement")),
    ("MEDICAL_HISTORY", "prior rotator cuff repair", r"\brotator cuff (?:repair|surgery)\b", ("rotator cuff",)),
    ("MEDICAL_HISTORY", "prior colectomy", r"\bcolectomy\b", ("colectomy",)),
    ("MEDICAL_HISTORY", "prior colonoscopy", r"\b(?:prior|previous|past).{0,15}colonoscopy\b", ("colonoscopy",)),
    ("MEDICAL_HISTORY", "prior cataract extraction", r"\bcataract.{0,15}(?:surgery|extraction|removal)\b", ("cataract",)),
    ("MEDICAL_HISTORY", "prior basal cell carcinoma removal", r"\bbasal cell\b|\bbcc\b", ("basal cell",)),
    ("MEDICAL_HISTORY", "prior neck surgery", r"\bneck surgery\b", ("neck surgery",)),
    ("MEDICAL_HISTORY", "history of coronary artery bypass graft", r"\bcabg\b|\bbypass (?:surgery|graft)\b|\bcoronary artery bypass\b", ("cabg", "bypass")),
    ("MEDICAL_HISTORY", "motor vehicle accident", r"\b(?:motor vehicle accident|mva|car (?:accident|crash))\b", ("mva", "car accident")),
    ("MEDICAL_HISTORY", "smoking", r"\bsmok(?:e|es|ing|er)\b", ("smok",)),
    ("MEDICAL_HISTORY", "alcohol use", r"\balcohol\b.{0,20}\b(?:use|drink|consumption)\b", ("alcohol",)),
    ("MEDICAL_HISTORY", "seasonal allergies", r"\bseasonal allergies?\b|\bhay fever\b", ("seasonal allerg",)),
    ("MEDICAL_HISTORY", "stress", r"\bstress(?:ful|ed)?\b.{0,30}\b(?:at work|job|family|recent)\b", ("stress",)),
    # ── Locations (ACI-Bench) ─────────────────────────────────────────────────
    ("LOCATION", "top of head", r"\btop of (?:my |the )?head\b", ("top of", "head")),
    ("LOCATION", "throat", r"\bthroat\b", ("throat",)),
    ("LOCATION", "lungs", r"\blungs?\b", ("lung",)),
    ("LOCATION", "sinuses", r"\bsinuses?\b", ("sinus",)),
    ("LOCATION", "right chest", r"\bright chest\b|\bright side of (?:my )?chest\b", ("right", "chest")),
    ("LOCATION", "head", r"\bhead\b", ("head",)),
    ("LOCATION", "behind left knee", r"\bbehind (?:my )?left knee\b", ("left knee",)),
    ("LOCATION", "chest", r"\bchest\b", ("chest",)),
    ("LOCATION", "heart", r"\bheart\b", ("heart",)),
    ("LOCATION", "abdomen", r"\babdomen\b|\babdominal\b", ("abdomen",)),
    ("LOCATION", "stomach", r"\bstomach\b", ("stomach",)),
    ("LOCATION", "right lower quadrant", r"\bright lower quadrant\b|\brlq\b", ("right lower quadrant",)),
    ("LOCATION", "right upper quadrant", r"\bright upper quadrant\b|\bruq\b", ("right upper quadrant",)),
    ("LOCATION", "lower back", r"\blower back\b|\blumbar\b", ("lower back", "lumbar")),
    ("LOCATION", "lumbar spine", r"\blumbar spine\b", ("lumbar spine",)),
    ("LOCATION", "back", r"\bback\b", ("back",)),
    ("LOCATION", "neck", r"\bneck\b", ("neck",)),
    ("LOCATION", "right knee", r"\bright knee\b", ("right knee",)),
    ("LOCATION", "bilateral knees", r"\bbilateral knees?\b|\bboth knees?\b", ("bilateral knee",)),
    ("LOCATION", "right elbow", r"\bright elbow\b", ("right elbow",)),
    ("LOCATION", "lateral epicondyle", r"\blateral epicondyle\b", ("epicondyle",)),
    ("LOCATION", "right shoulder", r"\bright shoulder\b", ("right shoulder",)),
    ("LOCATION", "right humerus", r"\bright humerus\b|\bright upper arm\b", ("humerus",)),
    ("LOCATION", "right middle finger", r"\bright (?:middle )?finger\b", ("finger",)),
    ("LOCATION", "right leg", r"\bright leg\b", ("right leg",)),
    ("LOCATION", "right foot", r"\bright foot\b", ("right foot",)),
    ("LOCATION", "forearm", r"\bforearm\b", ("forearm",)),
    ("LOCATION", "lower extremities", r"\blower extremit(?:y|ies)\b|\blegs?\b", ("lower extrem",)),
    ("LOCATION", "ankles", r"\bankles?\b", ("ankle",)),
    ("LOCATION", "nose", r"\bnose\b", ("nose",)),
    # ── Lab results (ACI-Bench) ───────────────────────────────────────────────
    ("LAB_RESULT", "temperature ~101 f", r"\b101\s*(?:f|fahrenheit)?\b", ("101",)),
    ("LAB_RESULT", "temperature 37.4 c", r"\b37\.4\s*(?:c|celsius)?\b", ("37.4",)),
    ("LAB_RESULT", "elevated blood pressure", r"\b(?:blood pressure|bp).{0,15}\b(?:elevated|high|\d{3}/\d{2})\b", ("blood pressure",)),
    ("LAB_RESULT", "elevated hemoglobin a1c", r"\ba1c.{0,15}\b(?:elevated|high|\d)\b|\bhba1c.{0,15}\b(?:elevated|high)\b", ("a1c",)),
    ("LAB_RESULT", "elevated glucose", r"\bglucose.{0,15}\b(?:elevated|high)\b|\belevated glucose\b", ("glucose",)),
    ("LAB_RESULT", "elevated cholesterol", r"\bcholesterol.{0,15}\b(?:elevated|high)\b|\bhigh cholesterol\b", ("cholesterol",)),
    ("LAB_RESULT", "elevated creatinine", r"\bcreatinine.{0,15}\b(?:elevated|high)\b", ("creatinine",)),
    ("LAB_RESULT", "decreased ejection fraction", r"\b(?:decreased|reduced|diminished|low).{0,10}(?:ejection fraction|ef)\b|\bef.{0,10}(?:\d{2}%?|decreased|reduced)\b", ("ejection fraction",)),
    ("LAB_RESULT", "ekg normal", r"\bekg.{0,15}normal\b|\bnormal.{0,15}ekg\b", ("ekg", "normal")),
    ("LAB_RESULT", "ekg lvh", r"\bekg.{0,15}lvh\b|\blvh\b", ("lvh",)),
    ("LAB_RESULT", "chest x-ray unremarkable", r"\bchest (?:x-?ray|xray).{0,15}(?:unremarkable|normal|clear|negative)\b", ("chest x-ray", "normal")),
    ("LAB_RESULT", "lyme titer elevated", r"\blyme titer.{0,15}(?:elevated|positive)\b", ("lyme titer",)),
    ("LAB_RESULT", "rapid strep positive", r"\bstrep.{0,15}positive\b|\bpositive.{0,15}strep\b", ("strep", "positive")),
    ("LAB_RESULT", "hemoglobin a1c 8", r"\ba1c.{0,10}(?:of )?8\b", ("a1c", "8")),
    ("LAB_RESULT", "white blood cell count normal", r"\bwbc.{0,15}normal\b|\bwhite blood cell.{0,15}normal\b", ("wbc", "normal")),
)

