"""Deterministic edge/heuristic maps for human-style KG enrichment."""

from __future__ import annotations

LOCATION_PAIRS = {
    # ENT / respiratory
    "sore throat": "throat",
    "scratchy throat": "throat",
    "runny nose": "nose",
    "nasal congestion": "nose",
    "stuffy nose": "nose",
    "headache": "head",
    "top of head pain": "top of head",
    "wheezing": "lungs",
    "shortness of breath": "lungs",
    "fine crackles": "lungs",
    "sinus pressure": "sinuses",
    # Chest / cardiac
    "chest pain": "chest",
    "chest tightness": "chest",
    "pleuritic chest pain": "chest",
    "chest pain with coughing": "chest",
    "sharp pain with deep breath": "right chest",
    "systolic ejection murmur": "heart",
    "palpitations": "heart",
    "mitral regurgitation": "heart",
    # GI
    "abdominal pain": "abdomen",
    "bloating": "abdomen",
    "right lower quadrant tenderness": "right lower quadrant",
    "right upper quadrant tenderness": "right upper quadrant",
    "gastritis": "stomach",
    "gastric polyp": "stomach",
    "nausea": "abdomen",
    "cva tenderness": "back",
    # Musculoskeletal
    "back pain": "back",
    "lower back pain": "lower back",
    "lumbar tenderness": "lumbar spine",
    "lumbar strain": "lumbar spine",
    "acute lumbar strain": "lumbar spine",
    "back stiffness": "back",
    "knee pain": "right knee",
    "right knee pain": "right knee",
    "right knee effusion": "right knee",
    "right knee erythema": "right knee",
    "elbow pain": "right elbow",
    "right elbow pain": "right elbow",
    "right elbow lateral epicondylitis": "lateral epicondyle",
    "lateral epicondyle tenderness": "lateral epicondyle",
    "right upper arm pain": "right humerus",
    "right middle finger pain": "right middle finger",
    "right leg pain": "right leg",
    "right leg contusion": "right leg",
    "forearm pain": "forearm",
    # Edema locations
    "ankle swelling": "ankles",
    "peripheral edema": "lower extremities",
    "bilateral lower extremity edema": "lower extremities",
    "pitting edema": "lower extremities",
    # Other
    "tick bite": "behind left knee",
    "redness": "behind left knee",
    "tenderness": "behind left knee",
}

INDICATES_MAP = {
    # Respiratory / infectious
    "covid-19": [
        "dry cough", "cough", "fever", "sore throat", "fatigue", "shortness of breath",
        "loss of taste", "loss of smell", "headache", "muscle aches", "chills",
    ],
    "viral infection / common cold": ["nasal congestion", "stuffy nose", "runny nose", "fatigue"],
    "viral illness": ["fever", "cough", "sore throat", "fatigue", "muscle aches", "chills"],
    "upper respiratory infection": ["cough", "sore throat", "runny nose", "nasal congestion"],
    "respiratory infection": ["cough", "dry cough", "fever", "shortness of breath", "yellow sputum"],
    "asthma exacerbation": ["wheezing", "shortness of breath", "chest tightness", "nocturnal wheezing"],
    "copd exacerbation": ["shortness of breath", "wheezing", "cough", "yellow sputum", "mucus production"],
    "copd": ["shortness of breath", "wheezing", "dyspnea on exertion"],
    # Cardiac
    "coronary artery disease": ["chest pain", "shortness of breath", "dyspnea on exertion", "fatigue"],
    "congestive heart failure exacerbation": [
        "shortness of breath", "dyspnea on exertion", "peripheral edema",
        "bilateral lower extremity edema", "ankle swelling", "weight gain",
        "pitting edema", "fine crackles",
    ],
    "heart disease concern": ["chest pain", "breathing faster", "difficulty deep breathing", "palpitations"],
    "pumping dysfunction": ["shortness of breath", "fatigue", "peripheral edema"],
    "uncontrolled hypertension": ["headache", "dizziness", "elevated blood pressure"],
    "hypertension": ["headache", "elevated blood pressure"],
    # GI
    "anemia": ["lightheadedness", "fatigue", "decreased appetite", "dizziness"],
    "gastritis": ["abdominal pain", "nausea", "bloating", "decreased appetite"],
    "acid reflux flare": ["abdominal pain", "nausea", "bloating"],
    "kidney stones recurrence": ["hematuria", "abdominal pain", "nausea", "vomiting", "back pain", "cva tenderness"],
    # Musculoskeletal
    "lumbar strain": ["back pain", "lower back pain", "back stiffness", "decreased range of motion", "lumbar tenderness"],
    "acute lumbar strain": ["back pain", "lower back pain", "back stiffness", "pain with bending"],
    "arthritis exacerbation": ["joint pain", "knee pain", "swelling", "decreased range of motion"],
    "right elbow lateral epicondylitis": ["elbow pain", "right elbow pain", "forearm pain", "decreased range of motion"],
    "right leg contusion": ["right leg pain", "bruising", "swelling"],
    # Endocrine
    "hyperglycemia": ["fatigue", "high blood sugar", "nausea", "decreased appetite"],
    "newly diagnosed diabetes": ["fatigue", "high blood sugar", "weight loss"],
    # Infectious
    "tick bite": ["redness", "tenderness", "soreness", "rash"],
    "lyme disease": ["rash", "fatigue", "joint pain", "headache"],
    "strep infection": ["sore throat", "fever"],
}

TREATMENT_TARGETS = {
    # Respiratory
    "insulin": [("type 1 diabetes", "MEDICAL_HISTORY")],
    "decongestants": [("nasal congestion", "SYMPTOM"), ("runny nose", "SYMPTOM")],
    "tylenol": [("fever", "SYMPTOM"), ("headache", "SYMPTOM"), ("back pain", "SYMPTOM"), ("knee pain", "SYMPTOM")],
    "tylenol cold": [("viral infection / common cold", "DIAGNOSIS"), ("nasal congestion", "SYMPTOM")],
    "self-isolation": [("covid-19", "DIAGNOSIS")],
    "14-day isolation": [("covid-19", "DIAGNOSIS")],
    "ventolin": [("asthma", "MEDICAL_HISTORY"), ("wheezing", "SYMPTOM"), ("shortness of breath", "SYMPTOM")],
    "spiriva": [("copd", "MEDICAL_HISTORY")],
    "maintenance inhaler": [("asthma", "MEDICAL_HISTORY"), ("copd", "MEDICAL_HISTORY")],
    "rescue inhaler": [("asthma exacerbation", "DIAGNOSIS"), ("shortness of breath", "SYMPTOM")],
    "rescue puffer": [("asthma exacerbation", "DIAGNOSIS"), ("shortness of breath", "SYMPTOM")],
    "combivent": [("copd", "DIAGNOSIS"), ("copd", "MEDICAL_HISTORY")],
    "albuterol inhaler": [("asthma", "DIAGNOSIS"), ("asthma", "MEDICAL_HISTORY"), ("copd", "DIAGNOSIS"), ("shortness of breath", "SYMPTOM")],
    "albuterol": [("asthma", "DIAGNOSIS"), ("copd", "DIAGNOSIS"), ("shortness of breath", "SYMPTOM")],
    "symbicort": [("asthma", "MEDICAL_HISTORY"), ("copd", "MEDICAL_HISTORY")],
    "prednisone taper": [("copd", "DIAGNOSIS"), ("asthma exacerbation", "DIAGNOSIS"), ("copd exacerbation", "DIAGNOSIS")],
    "steroids": [("asthma exacerbation", "DIAGNOSIS"), ("copd exacerbation", "DIAGNOSIS")],
    "smoking cessation": [("copd", "DIAGNOSIS"), ("copd", "MEDICAL_HISTORY"), ("smoking", "MEDICAL_HISTORY")],
    # Cardiac
    "lasix": [("congestive heart failure", "MEDICAL_HISTORY"), ("congestive heart failure exacerbation", "DIAGNOSIS"), ("edema", "SYMPTOM"), ("hypertension", "MEDICAL_HISTORY")],
    "carvedilol": [("congestive heart failure", "MEDICAL_HISTORY"), ("hypertension", "MEDICAL_HISTORY")],
    "digoxin": [("congestive heart failure", "MEDICAL_HISTORY"), ("atrial fibrillation", "MEDICAL_HISTORY")],
    "lisinopril": [("hypertension", "MEDICAL_HISTORY"), ("hypertension", "DIAGNOSIS"), ("congestive heart failure", "MEDICAL_HISTORY")],
    "norvasc": [("hypertension", "MEDICAL_HISTORY"), ("hypertension", "DIAGNOSIS")],
    "toprol": [("hypertension", "MEDICAL_HISTORY"), ("hypertension", "DIAGNOSIS")],
    "aspirin": [("coronary artery disease", "DIAGNOSIS"), ("coronary artery disease", "MEDICAL_HISTORY")],
    "diuretic": [("hypertension", "MEDICAL_HISTORY"), ("congestive heart failure", "MEDICAL_HISTORY")],
    # Cholesterol
    "atorvastatin": [("high cholesterol", "MEDICAL_HISTORY"), ("hypercholesterolemia", "MEDICAL_HISTORY")],
    "statin": [("high cholesterol", "MEDICAL_HISTORY"), ("hypercholesterolemia", "MEDICAL_HISTORY")],
    # GI
    "omeprazole": [("gastroesophageal reflux", "MEDICAL_HISTORY"), ("acid reflux flare", "DIAGNOSIS"), ("gastritis", "DIAGNOSIS")],
    "protonix": [("gastritis", "DIAGNOSIS"), ("gastroesophageal reflux", "MEDICAL_HISTORY")],
    "pepcid": [("gastroesophageal reflux", "MEDICAL_HISTORY"), ("acid reflux flare", "DIAGNOSIS")],
    "avoid nsaids": [("gastritis", "DIAGNOSIS")],
    "avoid alcohol": [("gastritis", "DIAGNOSIS")],
    "caffeine reduction": [("gastritis", "DIAGNOSIS"), ("acid reflux flare", "DIAGNOSIS")],
    # Endocrine
    "metformin": [("type 2 diabetes", "MEDICAL_HISTORY"), ("newly diagnosed diabetes", "DIAGNOSIS"), ("hyperglycemia", "DIAGNOSIS")],
    "synthroid": [("hypothyroidism", "MEDICAL_HISTORY")],
    "home blood sugar monitoring": [("type 2 diabetes", "MEDICAL_HISTORY"), ("newly diagnosed diabetes", "DIAGNOSIS")],
    "dietary modifications": [("type 2 diabetes", "MEDICAL_HISTORY"), ("hypertension", "MEDICAL_HISTORY"), ("hyperglycemia", "DIAGNOSIS"), ("prediabetes", "MEDICAL_HISTORY")],
    "lifestyle modifications": [("hypertension", "MEDICAL_HISTORY"), ("prediabetes", "MEDICAL_HISTORY"), ("type 2 diabetes", "MEDICAL_HISTORY")],
    # Pain / MSK
    "ibuprofen": [("back pain", "SYMPTOM"), ("knee pain", "SYMPTOM"), ("elbow pain", "SYMPTOM"), ("joint pain", "SYMPTOM"), ("headache", "SYMPTOM")],
    "meloxicam": [("arthritis", "MEDICAL_HISTORY"), ("arthritis exacerbation", "DIAGNOSIS"), ("joint pain", "SYMPTOM"), ("knee pain", "SYMPTOM")],
    "tramadol": [("back pain", "SYMPTOM"), ("joint pain", "SYMPTOM")],
    "lortab": [("back pain", "SYMPTOM"), ("knee pain", "SYMPTOM")],
    "painkillers": [("chest pain", "SYMPTOM"), ("headache", "SYMPTOM"), ("back pain", "SYMPTOM")],
    "nsaids": [("chest pain", "SYMPTOM"), ("headache", "SYMPTOM"), ("back pain", "SYMPTOM"), ("knee pain", "SYMPTOM")],
    "physical therapy": [("back pain", "SYMPTOM"), ("lumbar strain", "DIAGNOSIS"), ("acute lumbar strain", "DIAGNOSIS"), ("knee pain", "SYMPTOM"), ("arthritis exacerbation", "DIAGNOSIS")],
    "rest": [("lumbar strain", "DIAGNOSIS"), ("acute lumbar strain", "DIAGNOSIS"), ("right leg contusion", "DIAGNOSIS")],
    "ice": [("right leg contusion", "DIAGNOSIS"), ("knee pain", "SYMPTOM"), ("swelling", "SYMPTOM")],
    "sling": [("right proximal humerus fracture", "DIAGNOSIS")],
    "finger splint": [("right middle finger distal phalanx fracture", "DIAGNOSIS")],
    "home exercise": [("lumbar strain", "DIAGNOSIS"), ("back pain", "SYMPTOM")],
    # Psych
    "prozac": [("depression", "MEDICAL_HISTORY"), ("depression history", "MEDICAL_HISTORY")],
    "effexor": [("depression", "MEDICAL_HISTORY"), ("depression history", "MEDICAL_HISTORY")],
    "zoloft": [("depression", "MEDICAL_HISTORY"), ("depression history", "MEDICAL_HISTORY")],
    "neurontin": [("chronic back pain", "MEDICAL_HISTORY"), ("back pain", "SYMPTOM"), ("epilepsy", "MEDICAL_HISTORY")],
    "keppra": [("epilepsy", "MEDICAL_HISTORY")],
    "weekly counseling": [("depression", "MEDICAL_HISTORY"), ("depression history", "MEDICAL_HISTORY")],
    "weekly therapy": [("depression", "MEDICAL_HISTORY"), ("anxiety history", "MEDICAL_HISTORY")],
    "yoga": [("depression", "SYMPTOM"), ("back pain", "SYMPTOM"), ("chronic back pain", "MEDICAL_HISTORY")],
    # Other
    "salt water gargle": [("sore throat", "SYMPTOM")],
    "antibiotics": [("infection", "DIAGNOSIS"), ("respiratory infection", "DIAGNOSIS"), ("strep infection", "DIAGNOSIS")],
    "amoxicillin": [("strep infection", "DIAGNOSIS"), ("infection", "DIAGNOSIS")],
    "prophylactic antibiotics": [("tick bite", "DIAGNOSIS")],
    "allergy shots": [("seasonal allergies", "MEDICAL_HISTORY")],
    "supplemental oxygen": [("shortness of breath", "SYMPTOM"), ("copd exacerbation", "DIAGNOSIS")],
    "hydration": [("kidney stones recurrence", "DIAGNOSIS"), ("fever", "SYMPTOM")],
    "epipen": [("anaphylaxis history", "MEDICAL_HISTORY")],
    "allopurinol": [("gout", "MEDICAL_HISTORY")],
    "immunosuppressant medications": [("kidney transplant", "MEDICAL_HISTORY")],
}

CAUSE_LINKS = {
    # Respiratory / infectious
    "daycare exposure": ["viral infection / common cold", "viral illness", "covid-19"],
    "school exposure": ["viral illness", "upper respiratory infection", "covid-19"],
    "sick contact exposure": ["viral illness", "respiratory infection", "covid-19"],
    "sick contact - husband": ["viral illness", "respiratory infection"],
    "hospital worker": ["covid-19", "respiratory infection"],
    "smoking": ["copd", "copd exacerbation"],
    "smoking history": ["copd", "copd exacerbation"],
    "past smoking": ["copd"],
    "chemical plant work": ["respiratory infection", "shortness of breath"],
    "pollen trigger": ["asthma exacerbation", "wheezing"],
    "pollen exposure": ["asthma exacerbation", "wheezing"],
    "cold air trigger": ["asthma exacerbation", "wheezing"],
    "warm weather trigger": ["asthma exacerbation"],
    "exercise trigger": ["asthma exacerbation", "shortness of breath"],
    "carpets in home": ["asthma exacerbation", "wheezing"],
    "possible cat allergy": ["suspected allergies", "wheezing"],
    "hiking exposure": ["tick bite", "lyme disease"],
    "gardening exposure": ["tick bite"],
    # Cardiac
    "congestive heart failure": ["shortness of breath", "peripheral edema", "dyspnea on exertion"],
    "hypertension": ["headache"],
    "hypertension history": ["uncontrolled hypertension", "headache"],
    # GI
    "gastroesophageal reflux": ["acid reflux flare", "nausea", "abdominal pain"],
    "dietary indiscretion": ["acid reflux flare", "hyperglycemia"],
    "gallstones": ["abdominal pain", "right upper quadrant tenderness"],
    "kidney stones": ["kidney stones recurrence"],
    # MSK / injury
    "golfing": ["lumbar strain", "acute lumbar strain"],
    "moving boxes": ["lumbar strain", "knee pain"],
    "moving refrigerator": ["lumbar strain"],
    "bowling injury": ["right leg contusion"],
    "volleyball injury": ["right proximal humerus fracture"],
    "motor vehicle accident": ["right middle finger distal phalanx fracture"],
    "tennis exertion": ["right elbow lateral epicondylitis"],
    "yard work": ["back pain", "lumbar strain"],
    "prior back surgery": ["back pain", "chronic back pain"],
    "prior discectomy": ["back pain"],
    # Psych
    "stress": ["depression", "anxiety", "hypertension"],
    "depression history": ["depression"],
}

